baseURL = "https://fcrbpeter.com/"
languageCode = "en-us"
theme = "minimal"
title = "Peter Chan"
description = "Code for God | Worship for God"

[params]
    description = "Code for God | Worship for God"
    author = "Fcrb Peter"
    profilePic = "profile_pic.jpg"
    font = "Roboto"
    accent = "#52a427"
    showBorder = true
    backgroundColor = "#e5e5e5"
    githubUsername = "fcrbpeter"
    copyright = "&copy; 2021 Chan Ping Hung"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.icon]]
    url = "mailto:peter@mwh.hk"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/fcrbpeter"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/fcrbpeter/"
    name = "fab fa-linkedin"
    weight = 4
